version: "{build}"

hosts:
  quic.clemente.io: 127.0.0.1

image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\mholt\caddy

environment:
  APPVEYOR_RDP_PASSWORD: Pa$$w0rd

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off

test_script:
  - gometalinter --install
  - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests --vendor ./...
  - vendorcheck ./...
  - go test -race ./...

after_test:
  - golint ./...

deploy: off
